import { Project } from '@/types/project';

// Mock project data for the dashboard
export const MOCK_PROJECTS: Project[] = [
    {
        id: '1',
        name: 'Villa Renovation - Al Nakheel',
        type: 'Carpentry',
        type_ar: 'نجارة',
        location: 'Riyadh',
        location_ar: 'الرياض',
        date: '2024-01-15',
        status: 'completed',
    },
    {
        id: '2',
        name: 'Office Electrical Installation',
        type: 'Electrical',
        type_ar: 'كهربائي',
        location: 'Jeddah',
        location_ar: 'جدة',
        date: '2024-02-20',
        status: 'in_progress',
    },
    {
        id: '3',
        name: 'Hotel Plumbing Maintenance',
        type: 'Plumbing',
        type_ar: 'سباكة',
        location: 'Dubai',
        location_ar: 'دبي',
        date: '2024-03-10',
        status: 'pending',
    },
    {
        id: '4',
        name: 'Mall HVAC System Upgrade',
        type: 'HVAC',
        type_ar: 'تكييف',
        location: 'Abu Dhabi',
        location_ar: 'أبو ظبي',
        date: '2024-01-25',
        status: 'completed',
    },
    {
        id: '5',
        name: 'Residential Painting Project',
        type: 'Painting',
        type_ar: 'دهان',
        location: 'Riyadh',
        location_ar: 'الرياض',
        date: '2024-02-15',
        status: 'in_progress',
    },
    {
        id: '6',
        name: 'School Flooring Installation',
        type: 'Flooring',
        type_ar: 'أرضيات',
        location: 'Dammam',
        location_ar: 'الدمام',
        date: '2024-03-05',
        status: 'pending',
    },
    {
        id: '7',
        name: 'Garden Landscaping - Compound',
        type: 'Gardening',
        type_ar: 'حدائق',
        location: 'Jeddah',
        location_ar: 'جدة',
        date: '2024-01-30',
        status: 'completed',
    },
    {
        id: '8',
        name: 'Restaurant Kitchen Setup',
        type: 'Carpentry',
        type_ar: 'نجارة',
        location: 'Doha',
        location_ar: 'الدوحة',
        date: '2024-02-28',
        status: 'in_progress',
    },
    {
        id: '9',
        name: 'Apartment Electrical Rewiring',
        type: 'Electrical',
        type_ar: 'كهربائي',
        location: 'Manama',
        location_ar: 'المنامة',
        date: '2024-03-12',
        status: 'pending',
    },
    {
        id: '10',
        name: 'Warehouse Flooring Repair',
        type: 'Flooring',
        type_ar: 'أرضيات',
        location: 'Riyadh',
        location_ar: 'الرياض',
        date: '2024-01-20',
        status: 'completed',
    },
];
